
package services.login_service.Services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LogRequestPortType", targetNamespace = "http://ChristianRosalesTest.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public class LogRequestPortType {


    /**
     * 
     * @param loginRequest
     * @return
     *     returns Services.LoginResponse
     */
    @WebMethod(operationName = "Login", action = "http://ChristianRosalesTest.com")
    @WebResult(name = "LoginResponse", targetNamespace = "http://ChristianRosalesTest.com", partName = "LoginRespond")
    public LoginResponse login(
        @WebParam(name = "LoginComplete", targetNamespace = "http://ChristianRosalesTest.com", partName = "LoginRequest")
        LoginComplete loginRequest)
    {
        LoginResponse response = new LoginResponse();
        if(loginRequest.getUsername().equals("Bob"))
            if(loginRequest.getPassword().equals("Joe"))
            response.setCompleted("Login Successful!");
            else
                response.setCompleted("Invalid Password");
        else
            response.setCompleted("That username doesn't exist.");
        return response;
    }

}
