
package client.Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LogRequestPortType", targetNamespace = "http://ChristianRosalesTest.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LogRequestPortType {


    /**
     * 
     * @param loginRequest
     * @return
     *     returns Client.LoginResponse
     */
    @WebMethod(operationName = "Login", action = "http://ChristianRosalesTest.com")
    @WebResult(name = "LoginResponse", targetNamespace = "http://ChristianRosalesTest.com", partName = "LoginRespond")
    @Action(input = "http://ChristianRosalesTest.com", output = "http://ChristianRosalesTest.com/LogRequestPortType/LoginResponse")
    public LoginResponse login(
        @WebParam(name = "LoginComplete", targetNamespace = "http://ChristianRosalesTest.com", partName = "LoginRequest")
        LoginComplete loginRequest);

}
