
package client.Client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LogRequestPortTypeService", targetNamespace = "http://ChristianRosalesTest.com", wsdlLocation = "http://localhost:9876/login?wsdl")
public class LogRequestPortTypeService
    extends Service
{

    private final static URL LOGREQUESTPORTTYPESERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGREQUESTPORTTYPESERVICE_EXCEPTION;
    private final static QName LOGREQUESTPORTTYPESERVICE_QNAME = new QName("http://ChristianRosalesTest.com", "LogRequestPortTypeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9876/login?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGREQUESTPORTTYPESERVICE_WSDL_LOCATION = url;
        LOGREQUESTPORTTYPESERVICE_EXCEPTION = e;
    }

    public LogRequestPortTypeService() {
        super(__getWsdlLocation(), LOGREQUESTPORTTYPESERVICE_QNAME);
    }

    public LogRequestPortTypeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGREQUESTPORTTYPESERVICE_QNAME, features);
    }

    public LogRequestPortTypeService(URL wsdlLocation) {
        super(wsdlLocation, LOGREQUESTPORTTYPESERVICE_QNAME);
    }

    public LogRequestPortTypeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGREQUESTPORTTYPESERVICE_QNAME, features);
    }

    public LogRequestPortTypeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogRequestPortTypeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LogRequestPortType
     */
    @WebEndpoint(name = "LogRequestPortTypePort")
    public LogRequestPortType getLogRequestPortTypePort() {
        return super.getPort(new QName("http://ChristianRosalesTest.com", "LogRequestPortTypePort"), LogRequestPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogRequestPortType
     */
    @WebEndpoint(name = "LogRequestPortTypePort")
    public LogRequestPortType getLogRequestPortTypePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ChristianRosalesTest.com", "LogRequestPortTypePort"), LogRequestPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGREQUESTPORTTYPESERVICE_EXCEPTION!= null) {
            throw LOGREQUESTPORTTYPESERVICE_EXCEPTION;
        }
        return LOGREQUESTPORTTYPESERVICE_WSDL_LOCATION;
    }

}
